name: perpustakaan_app
description: Aplikasi Sistem Informasi Perpustakaan

# Versi Flutter yang digunakan
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Untuk mendukung lokalisasi (format tanggal bahasa Indonesia)
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.2
  
  # Networking
  http: ^1.1.0  # Untuk HTTP requests
  
  # Date & Time
  intl: ^0.19.0  # Untuk format tanggal
  
  # Image
  cached_network_image: ^3.2.0  # Untuk caching gambar

  # State Management (optional, jika diperlukan)
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# Konfigurasi Flutter
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

  # Fonts (optional)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
